from enum import Enum
from typing import Union

from pydantic import BaseModel


class ErrorModel(BaseModel):
    detail: Union[str, dict[str, str]]


class ErrorCode(str, Enum):
    RECORD_NOT_FOUND = "RECORD_NOT_FOUND"
    RECORD_ALREADY_EXISTS = "RECORD_ALREADY_EXISTS"

    INVALID_PASSWORD = "INVALID_PASSWORD"

    USER_ALREADY_VERIFIED = "USER_ALREADY_VERIFIED"
    USER_NOT_VERIFIED = "USER_NOT_VERIFIED"
    MISSING_TOKEN = "MISSING_TOKEN"

    LOGIN_BAD_CREDENTIALS = "LOGIN_BAD_CREDENTIALS"

    RESET_PASSWORD_BAD_TOKEN = "RESET_PASSWORD_BAD_TOKEN"
    VERIFY_USER_BAD_TOKEN = "VERIFY_USER_BAD_TOKEN"

    ORDER_IS_CONFIRMED = "ORDER_IS_CONFIRMED"

    FORBIDDEN_OPERATION = "FORBIDDEN_OPERATION"
